# personal_bpnet.py
# Author: Adam He <adamyhe@gmail.com>

"""
A subclass of bpnetlite.bpnet.BPNet that redoes the validation loop to work with a
PyTorch DataLoader, rather than having to load the whole validation set into memory
at once. Also, the model checkpoints save the optimizer state dict and epoch number
in addition to the model state dict, so that training can be resumed from a
checkpoint. The architecture (and therefore state_dict) is identical to BPNet, so
PersonalBPNet weights can be loaded directly into a standard BPNet instance (and
vice versa), as long as the same init arguments are used.
"""

import time

import numpy as np
import torch
from bpnetlite.bpnet import BPNet
from bpnetlite.losses import _mixture_loss
from bpnetlite.performance import calculate_performance_measures, pearson_corr
from tangermeme.predict import predict


class PersonalBPNet(BPNet):
    """
    A basic BPNet model with stranded profile and total count prediction.

    Identical architecture to `bpnetlite.bpnet.BPNet`, but with a `fit()` method that
    accepts a PyTorch DataLoader for validation data (instead of fixed tensors), which
    significantly improves the memory footprint of the validation step, and that
    checkpoints the optimizer state dict and epoch number alongside the model weights
    to support resuming training. Note that random data augmentations (jittering,
    reverse complement) should be turned off to return a fixed validation dataset.

    See `bpnetlite.bpnet.BPNet` for the model architecture and the meaning of the
    constructor parameters. Defaults for `n_outputs`, `n_control_tracks`, and
    `trimming` differ from BPNet's to match this project's typical use case
    (single-output, no controls).
    """

    def __init__(
        self, *args, n_outputs=1, n_control_tracks=0, n_layers=8, trimming=None, **kwargs
    ):
        super().__init__(
            *args,
            n_outputs=n_outputs,
            n_control_tracks=n_control_tracks,
            n_layers=n_layers,
            trimming=trimming if trimming is not None else 2**n_layers,
            **kwargs,
        )

    def fit(
        self,
        training_data,
        optimizer,
        scheduler=None,
        valid_data=None,
        max_epochs=100,
        batch_size=64,
        validation_iter=100,
        early_stopping=None,
        dtype=torch.bfloat16,
        device="cuda",
        verbose=True,
    ):
        """Fit the model to data and validate it periodically.

        This method controls the training of a BPNet model. It will fit the
        model to examples generated by the `training_data` DataLoader object
        and, if validation data is provided, will periodically validate the
        model against it and return those values. The periodicity can be
        controlled using the `validation_iter` parameter.

        Two versions of the model will be saved: the best model found during
        training according to the validation measures, and the final model
        at the end of training. Additionally, a log will be saved of the
        training and validation statistics, e.g. time and performance.

        Parameters
        ----------
        training_data: torch.utils.data.DataLoader
                A generator that produces examples to train on. If n_control_tracks
                is greater than 0, must product two inputs, otherwise must produce
                only one input.

        optimizer: torch.optim.Optimizer
                An optimizer to control the training of the model.

        scheduler: torch.optim.lr_scheduler._LRScheduler or None
                A scheduler to control the learning rate of the optimizer. Optional.

        valid_data: torch.utils.data.DataLoader
                A generator that produces examples to earlystop on. If n_control_tracks
                is greater than 0, must product two inputs, otherwise must produce
                only one input.

        max_epochs: int
                The maximum number of epochs to train for, as measured by the
                number of times that `training_data` is exhausted. Default is 100.

        batch_size: int
                The number of examples to include in each batch. Default is 64.

        validation_iter: int
                The number of batches to train on before validating against the
                entire validation set. When the validation set is large, this
                enables the total validating time to be small compared to the
                training time by only validating periodically. Default is 100.

        early_stopping: int or None
                Whether to stop training early. If None, continue training until
                max_epochs is reached. If an integer, continue training until that
                number of `validation_iter` ticks has been hit without improvement
                in performance. Default is None.

        verbose: bool
                Whether to print out the training and evaluation statistics during
                training. Default is True.
        """

        iteration = 0
        early_stop_count = 0
        best_loss = float("inf")
        self.logger.start()

        for epoch in range(max_epochs):
            tic = time.time()

            for data in training_data:
                if len(data) == 4:
                    X, X_ctl, y, labels = data
                    X_ctl = torch.abs(X_ctl).to(device).float()
                else:
                    X, y, labels = data
                    X_ctl = None

                X = X.to(device).float()
                y = torch.abs(y).to(device)

                # Clear the optimizer and set the model to training mode
                optimizer.zero_grad()
                self.train()

                # Run forward pass
                with torch.autocast(device_type=device, dtype=dtype):
                    y_hat_logits, y_hat_logcounts = self(X, X_ctl)
                    training_profile_loss_, training_count_loss_, loss = _mixture_loss(
                        y, y_hat_logits, y_hat_logcounts, self.count_loss_weight, labels
                    )
                    loss.backward()
                    optimizer.step()

                # Report measures if desired
                if verbose and iteration % validation_iter == 0:
                    train_time = time.time() - tic

                    with torch.no_grad():
                        self.eval()

                        tic = time.time()

                        # Initialize lists to store validation statistics
                        profile_corr = []
                        valid_mnll = []
                        valid_mse = []
                        pred_counts = []
                        obs_counts = []

                        # Loop over the validation data
                        for data in valid_data:
                            if len(data) == 3:
                                X_val, X_ctl_val, y_val = data
                                X_ctl_val = (torch.abs(X_ctl_val),)
                            else:
                                X_val, y_val = data
                                X_ctl_val = None

                            y_val = torch.abs(y_val)
                            y_profile, y_counts = predict(
                                self,
                                X_val,
                                args=X_ctl_val,
                                batch_size=batch_size,
                                device=device,
                                dtype=dtype,
                            )
                            obs_counts.append(y_val.sum(dim=(-2, -1)).reshape(-1, 1))
                            pred_counts.append(y_counts)

                            z = y_profile.shape
                            y_profile = y_profile.reshape(y_profile.shape[0], -1)
                            y_profile = torch.nn.functional.log_softmax(
                                y_profile, dim=-1
                            )
                            y_profile = y_profile.reshape(*z)

                            measures = calculate_performance_measures(
                                y_profile,
                                y_val,
                                y_counts,
                                kernel_sigma=7,
                                kernel_width=81,
                                measures=[
                                    "profile_mnll",
                                    "profile_pearson",
                                    "count_mse",
                                ],
                            )
                            profile_corr.append(measures["profile_pearson"])
                            valid_mnll.append(measures["profile_mnll"])
                            valid_mse.append(measures["count_mse"])

                        # Other metrics can be calculated in the loop, but
                        # count_corr needs to be calculated by storing the
                        # counts and then calculating the correlation at the end
                        count_corr = pearson_corr(
                            torch.cat(pred_counts).squeeze(),
                            torch.log(torch.cat(obs_counts).squeeze() + 1),
                        )

                        # Concatenate the lists of validation measures
                        profile_corr = torch.cat(profile_corr)
                        valid_mnll = torch.cat(valid_mnll)
                        valid_mse = torch.cat(valid_mse)
                        valid_loss = (
                            valid_mnll.mean() + self.count_loss_weight * valid_mse.mean()
                        )

                        valid_time = time.time() - tic

                        self.logger.add(
                            [
                                epoch,
                                iteration,
                                train_time,
                                valid_time,
                                training_profile_loss_.item(),
                                training_count_loss_.item(),
                                measures["profile_mnll"].mean().item(),
                                np.nan_to_num(profile_corr).mean(),
                                np.nan_to_num(count_corr).mean(),
                                measures["count_mse"].mean().item(),
                                (valid_loss < best_loss).item(),
                            ]
                        )

                        self.logger.save("{}.log".format(self.name))

                        # Save the model if it is the best so far
                        if valid_loss < best_loss:
                            torch.save(self.state_dict(), f"{self.name}.torch")
                            torch.save(
                                {
                                    "early_stop_count": early_stop_count,
                                    "epoch": epoch,
                                    "optimizer_state_dict": optimizer.state_dict(),
                                },
                                f"{self.name}.checkpoint.torch",
                            )
                            best_loss = valid_loss
                            early_stop_count = 0
                        else:
                            early_stop_count += 1

                if early_stopping is not None and early_stop_count >= early_stopping:
                    break

                iteration += 1

            if early_stopping is not None and early_stop_count >= early_stopping:
                break
            if scheduler is not None:
                scheduler.step()

        torch.save(self, "{}.final.torch".format(self.name))
