# clipnet_pytorch.py
# Author: Adam He <adamyhe@gmail.com>

"""
An implementation of ProCapNet as a subclass of bpnetlite.bpnet.BPNet. Its forward pass
is the same as BPNet, but implements a masked profile loss function as described in the
ProCapNet paper. Because the forward pass is the same, ProCapNet models can also be
loaded using the bpnetlite.bpnet.BPNet class (provided you pass in the same init args).
"""

import time

import numpy as np
import torch
from bpnetlite.bpnet import BPNet
from bpnetlite.logging import Logger
from bpnetlite.performance import calculate_performance_measures
from tangermeme.predict import predict

from .losses import _mixture_loss_masked


class ProCapNet(BPNet):
    def __init__(
        self,
        *args,
        n_filters=512,
        n_outputs=2,
        n_control_tracks=0,
        count_loss_weight=100,
        verbose=True,
        **kwargs,
    ):
        super().__init__(
            *args,
            n_filters=n_filters,
            n_outputs=n_outputs,
            n_control_tracks=n_control_tracks,
            count_loss_weight=count_loss_weight,
            **kwargs,
        )
        self.logger = Logger(
            [
                "Epoch",
                "Iteration",
                "Training Time",
                "Validation Time",
                "Training MNLL",
                "Training Count MSE",
                "Validation MNLL",
                "Validation Count MSE",
                "Validation Profile JSD",
                "Validation Count Pearson",
                "Saved?",
            ],
            verbose=verbose,
        )

    def fit(
        self,
        training_data,
        optimizer,
        scheduler=None,
        X_valid=None,
        X_ctl_valid=None,
        y_valid=None,
        y_has_mask=True,
        max_epochs=100,
        batch_size=64,
        dtype="float32",
        device="cuda",
        early_stopping=None,
    ):
        """Fit the model to data and validate it periodically.

        This method controls the training of a BPNet model. It will fit the
        model to examples generated by the `training_data` DataLoader object
        and, if validation data is provided, will validate the model against
        it at the end of each epoch and return those values.

        Two versions of the model will be saved: the best model found during
        training according to the validation measures, and the final model
        at the end of training. Additionally, a log will be saved of the
        training and validation statistics, e.g. time and performance.

        Parameters
        ----------
        training_data: torch.utils.data.DataLoader
            A generator that produces examples to train on. If n_control_tracks
            is greater than 0, must product two inputs, otherwise must produce
            only one input.

        optimizer: torch.optim.Optimizer
            An optimizer to control the training of the model.

        scheduler: torch.optim.lr_scheduler, optional
            An optional learning rate scheduler which changes the learning rate
            across batches. If None, do not use a scheduler. Default is None.

        X_valid: torch.tensor or None, shape=(n, 4, 2114)
            A block of sequences to validate on periodically. If None, do not
            perform validation. Default is None.

        X_ctl_valid: torch.tensor or None, shape=(n, n_control_tracks, 2114)
            A block of control sequences to validate on periodically. If
            n_control_tracks is None, pass in None. Default is None.

        y_valid: torch.tensor or None, shape=(n, n_outputs, 1000)
            A block of signals to validate against. Must be provided if
            X_valid is also provided. Default is None.

        y_has_mask: bool
            Whether the output y tracks will contain a boolean mask for excluding
            positions from profile loss calculations. The final output track
            will be treated as a boolean mask, whereas the other tracks will be
            processed as normal. Default is True.

        max_epochs: int
            The maximum number of epochs to train for, as measured by the
            number of times that `training_data` is exhausted. Default is 100.

        batch_size: int, optional
            The number of examples to include in each batch. Default is 64.

        dtype: str or torch.dtype
            The torch.dtype to use when training. Usually, this will be torch.float32
            or torch.bfloat16. Default is torch.float32.

        device: str
            The device to use for training and inference. Typically, this will be
            'cuda' but can be anything supported by torch. Default is 'cuda'.

        early_stopping: int or None, optional
            Whether to stop training early. If None, continue training until
            max_epochs is reached. If an integer, continue training until that
            number of epochs has been hit without improvement in performance.
            Default is None.
        """

        if y_valid is not None and y_has_mask:
            y_valid = y_valid[:, : self.n_outputs, :]

        if X_ctl_valid is not None:
            X_ctl_valid = (X_ctl_valid,)

        dtype = getattr(torch, dtype) if isinstance(dtype, str) else dtype

        iteration = 0
        early_stop_count = 0
        best_loss = float("inf")
        self.logger.start()

        for epoch in range(max_epochs):
            tic = time.time()

            for data in training_data:
                X, y, labels = data[0], data[-2], data[-1]
                if y_has_mask:
                    mask = y[:, -1, :] == 1
                else:
                    mask = None
                y = y[:, : self.n_outputs, :]
                X_ctl = data[1].to(device) if len(data) == 4 else None

                X = X.to(device).float()
                y = y.to(device)

                # Clear the optimizer and set the model to training mode
                optimizer.zero_grad()
                self.train()

                # Make one training step
                with torch.autocast(device_type=device, dtype=dtype):
                    y_hat_logits, y_hat_logcounts = self(X, X_ctl)

                    training_profile_loss_, training_count_loss_, loss = (
                        _mixture_loss_masked(
                            y,
                            y_hat_logits,
                            y_hat_logcounts,
                            self.count_loss_weight,
                            labels,
                            mask.to(device) if mask is not None else None,
                        )
                    )

                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(self.parameters(), 1)
                    optimizer.step()

                iteration += 1

            train_time = time.time() - tic

            # Validate the model at the end of the epoch
            with torch.no_grad():
                self.eval()
                tic = time.time()

                y_hat_logits, y_hat_logcounts = predict(
                    self,
                    X_valid,
                    args=X_ctl_valid,
                    batch_size=batch_size,
                    dtype=dtype,
                    device=device,
                )

                valid_profile_loss, valid_count_loss, valid_loss = _mixture_loss_masked(
                    y_valid, y_hat_logits, y_hat_logcounts, self.count_loss_weight, labels=None, mask=None
                )

                measures = calculate_performance_measures(
                    y_hat_logits,
                    y_valid,
                    y_hat_logcounts,
                    kernel_sigma=7,
                    kernel_width=81,
                    measures=["profile_jsd", "count_pearson"],
                )

                valid_profile_jsd = np.nan_to_num(measures["profile_jsd"])
                valid_count_corr = np.nan_to_num(measures["count_pearson"])
                valid_time = time.time() - tic

                self.logger.add(
                    [
                        epoch,
                        iteration,
                        train_time,
                        valid_time,
                        training_profile_loss_.item(),
                        training_count_loss_.item(),
                        valid_profile_loss.item(),
                        valid_count_loss.item(),
                        valid_profile_jsd.mean(),
                        valid_count_corr.mean(),
                        (valid_loss < best_loss).item(),
                    ]
                )

                self.logger.save("{}.log".format(self.name))

                if valid_loss < best_loss:
                    torch.save(self.state_dict(), "{}.torch".format(self.name))
                    best_loss = valid_loss
                    early_stop_count = -1

            if scheduler is not None:
                scheduler.step(valid_loss)

            early_stop_count += 1
            if early_stopping is not None and early_stop_count >= early_stopping:
                break

        torch.save(self.state_dict(), "{}.final.torch".format(self.name))
